### ISSUE TITLE
doesn't work with jsdom 0.2.0

### ISSUE THREAD

**Issue by gerad** [mape/node-scraper#4]
I'm getting issues when trying to run the example app with Node 0.4.0 and JSDom 0.2.0..

Here's the stacktrace

```
TypeError: Cannot read property 'prototype' of undefined
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/browser/index.js:84:16
    at String.<anonymous> ([object Context]:2500:12)
    at Function.each ([object Context]:692:29)
    at Object.add ([object Context]:2478:10)
    at [object Context]:2907:17
    at Function.each ([object Context]:692:29)
    at Object.each ([object Context]:155:17)
    at Object.one ([object Context]:2906:15)
    at Object.bind ([object Context]:2896:34)
    at [object Context]:3106:18
    at [object Context]:4376:2
    at Object.javascript (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/languages/javascript.js:17:14)
    at Object._eval (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:1195:46)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:43:20
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
    at afterRead (fs.js:840:12)
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /usr/local/lib/node/.npm/scraper/0.0.8/package/lib/scraper.js:58:7
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom.js:151:30
    at Object.<anonymous> (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/events.js:274:17)
    at Object.dispatchEvent (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:415:55)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:56:15
    at Object.check (/usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:235:34)
    at /usr/local/lib/node/.npm/jsdom/0.2.0/package/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:86:5)
    at [object Object].emit (events.js:39:17)
```

**Comment by mape** [comment]
Have you tried it with latest stable?

**Comment by gerad** [comment]
Yeah, fails on node 0.4.2 with jsdom 0.2.0... works fine with jsdom 0.1.23.

**Comment by mape** [comment]
Is that when using the examples or scraping a different site?

**Comment by gerad** [comment]
Just the first simple twitter example in your README.

**Comment by gerad** [comment]
Seems like it's probably a JSDOM issue.

**Comment by mape** [comment]
I don't have that issue though, but yeah, seems jsdom doesn't want to play.

**Comment by jpiulac** [comment]
Had the same issue. fixed with change to scraper.js

replaced __dirname+'/../deps/jquery-1.3.2.js'
with 'http://code.jquery.com/jquery-1.4.2.min.js' 

seems to be an issue loading the file in jsdom.jQuerify call - path is correct and permissions are fine so not sure what the problem is.

**Comment by EvanCarroll** [comment]
This issue isn't solved. I had the same problem with `jsdom 0.2.0` , and I solved it with @jma3s suggestion.

```
$ node --version
v0.4.7
```

I actually upgrade though to `jquery-1.6.0`

**Comment by sindresorhus** [comment]
Tried @jma3s fix, but still get that error.

```
TypeError: Cannot read property 'prototype' of undefined
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/browser/index.js:84:16
    at String.<anonymous> ([object Context]:2500:12)
    at Function.each ([object Context]:692:29)
    at Object.add ([object Context]:2478:10)
    at [object Context]:2907:17
    at Function.each ([object Context]:692:29)
    at Object.each ([object Context]:155:17)
    at Object.one ([object Context]:2906:15)
    at Object.bind ([object Context]:2896:34)
    at [object Context]:3106:18
    at [object Context]:4376:2
    at Object.javascript (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/languages/javascript.js:17:14)
    at Object._eval (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:1195:46)
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:43:20
    at Object.check (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:235:11)
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
    at afterRead (fs.js:878:12)
    at wrapper (fs.js:245:17)
TypeError: undefined is not a function
    at CALL_NON_FUNCTION (native)
    at /Users/mofle/node_modules/scraper/lib/scraper.js:58:7
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom.js:151:7
    at Object.<anonymous> (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/events.js:274:17)
    at Object.dispatchEvent (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:415:55)
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:56:15
    at Object.check (/Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:235:11)
    at /Users/mofle/node_modules/scraper/node_modules/jsdom/lib/jsdom/level2/html.js:251:12
    at [object Object].<anonymous> (fs.js:107:5)
    at [object Object].emit (events.js:61:17)
```

**Comment by dkordik** [comment]
Mine was fixed by updating jQuery ala @jma3s. I used 1.6.1.

**Comment by EvanCarroll** [comment]
@mape could we get this patched with @jma3s's suggestion and the latest version of jQuery?

**Comment by mape** [comment]
The scraper is now updated to use jQuery 1.6.1 and is pushed to npm.

@mofle Do you get that error with all pages? And are you using latest jsdom?

**Comment by muloka** [comment]
There is also an issue with jsdom 0.2.0 which has been fixed in 0.2.1 though it has not been yet pushed to npm.  Also line 57 of scrape.js is still referring to jQuery 1.3.2.   

After switching it to the supplied 1.6.1 library and changing the require statement to point to jsdom@0.2.1, scraper is working as expected.

p.s.: I'm currently using node v0.5.0-pre.

**Comment by mape** [comment]
Silly me, pushed update that uses jQuery 1.61.

**Comment by EyePulp** [comment]
I did a manual uninstall of jsdom via npm: npm uninstall jsdom from within the scraper directory  project/node_modules/scraper

and then ran this:
npm install https://github.com/tmpvar/jsdom/tarball/4cf155a1624b3fb54b2eec536a0c060ec1bab4ab
out at the upper level project/  - it seems to have fixed it also.  (it has the jsdom 0.2.1 fix)
